#!/usr/bin/env bash

case "${1-}" in
  install )
    stack install
    ;;

  build )
    stack build
    ;;

  clean )
    stack clean
    ;;

  distclean )
    rm -rf .stack-work
    rm -rf hindent-elm.cabal
    rm -rf stack.yaml.lock
    ;;

  format )
    #mapfile -t files < <(fdfind -c never -t f ".hs")

    ## Archlinux with fd
    mapfile -t files < <(fd -c never -t f ".hs")

    hindent-elm "${files[@]}"
    ;;

  *)
    cat << EOF
Usage: $(pwd)
  ./main install
  ./main build
  ./main clean
  ./main distclean
  ./main format
EOF
    ;;
esac
