#!/usr/bin/env bash

case "${1-}" in
  install )
    stack install
    ;;

  build )
    stack build
    ;;

  distclean )
    rm -rf .stack-work
    rm -rf hindent-elm.cabal
    rm -rf stack.yaml.lock
    ;;

  *)
    cat << EOF
Usage: $(pwd)
  ./main install
  ./main build
  ./main distclean
EOF
    ;;
esac
