#!/usr/bin/env bash

case "${1-}" in
  install )
    stack install
    ;;

  build )
    stack -j 8 build
    ;;

  clean )
    stack clean
    ;;

  distclean )
    stack clean
    rm -rf .stack-work
    rm -rf hindent-elm.cabal
    rm -rf stack.yaml.lock
    ;;

  format )
    if command -v fdfind > /dev/null
    then
      fd_="fdfind"
    elif command -v fd > /dev/null
    then
      fd_="fdfind"
    else
      echo "please install fd"
      echo "https://github.com/sharkdp/fd"
      exit 1
    fi
    mapfile -t files < <("${fd_}" -c never -t f ".hs")

    hindent-elm "${files[@]}"
    ;;

  *)
    cat << EOF
Usage: $(pwd)
  ./main install
  ./main build
  ./main clean
  ./main distclean
  ./main format
EOF
    ;;
esac
