name: hindent-elm
version: "0.1.0"
dependencies:
- base >= 4.7 && <5
- containers
- Cabal
- filepath
- directory
- haskell-src-exts >= 1.20
- monad-loops
- mtl
- bytestring
- utf8-string
- transformers
- exceptions
- text
- yaml
