name: hindent-elm
version: "0.1.8"
default-extensions:
- LambdaCase
- OverloadedStrings
- StrictData
ghc-options:
- -fwrite-ide-info
- -hiedir=.hie
- -Wall
dependencies:
- Cabal
- base
- bytestring
- containers
- deepseq
- directory
- exceptions
- filepath
- ghc-prim
- haskell-src-exts
- monad-loops
- mtl
- optparse-applicative
- path
- path-io
- text
- transformers
- unix-compat
- utf8-string
- yaml
library:
  source-dirs: src
executables:
  hindent-elm:
    main: Main.hs
    source-dirs: app
    dependencies:
    - hindent-elm
